[[redirects]]
from = "/"
to = "/install-kirami.py"
status = 200
force = true
headers = { Content-Type = "text/plain; charset=utf-8" }

[build]
ignore = "git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF install-kirami.py"
